INSERT INTO DEVELOPERS VALUES (1, 'Nataliia Hrybyniuk', 28, 'female');
INSERT INTO DEVELOPERS VALUES (2, 'Svitlana Gorodok', 30, 'female');
INSERT INTO DEVELOPERS VALUES (3, 'Volodymyr Ivanov', 42, 'male');
INSERT INTO DEVELOPERS VALUES (4, 'Ivan Pavlov', 33, 'male');
INSERT INTO DEVELOPERS VALUES (5, 'Serhii Kotikov', 29, 'male');
INSERT INTO DEVELOPERS VALUES (6, 'Olga Sulin', 40, 'female');

INSERT INTO SKILLS VALUES (1, 'Java', 'Junior');
INSERT INTO SKILLS VALUES (2, 'Java', 'Middle');
INSERT INTO SKILLS VALUES (3, 'C++', 'Middle');
INSERT INTO SKILLS VALUES (4, 'React', 'Senior');
INSERT INTO SKILLS VALUES (5, 'Python', 'Junior');
INSERT INTO SKILLS VALUES (6, 'Java', 'Senior');

INSERT INTO DEVELOPERS_SKILLS VALUES (1, 6);
INSERT INTO DEVELOPERS_SKILLS VALUES (1, 4);
INSERT INTO DEVELOPERS_SKILLS VALUES (2, 1);
INSERT INTO DEVELOPERS_SKILLS VALUES (3, 5);
INSERT INTO DEVELOPERS_SKILLS VALUES (3, 3);
INSERT INTO DEVELOPERS_SKILLS VALUES (4, 2);
INSERT INTO DEVELOPERS_SKILLS VALUES (5, 4);
INSERT INTO DEVELOPERS_SKILLS VALUES (5, 2);
INSERT INTO DEVELOPERS_SKILLS VALUES (5, 1);

INSERT INTO COMPANIES VALUES (1, 'Luxoft', 'Dariia Kot');
INSERT INTO COMPANIES VALUES (2, 'GoIT', 'Mariia Petrova');
INSERT INTO COMPANIES VALUES (3, 'SoftServe', 'Olexander Zuma');
INSERT INTO COMPANIES VALUES (4, 'Datas', 'Zoia Sonceva');
INSERT INTO COMPANIES VALUES (5, 'BMS', 'Dariia Ivanova');
INSERT INTO COMPANIES VALUES (6, 'EPAM', 'Pavlo Polish');
INSERT INTO COMPANIES VALUES (7, 'MateIT', 'Oksana Selivanova');

INSERT INTO CUSTOMERS VALUES (1, 'OTP Bank', '0984758963');
INSERT INTO CUSTOMERS VALUES (2, 'PrivatBank', '0639854236');
INSERT INTO CUSTOMERS VALUES (3, 'Monobank', '0502589631');
INSERT INTO CUSTOMERS VALUES (4, 'Metro', '0507411236');
INSERT INTO CUSTOMERS VALUES (5, 'Ashan', '0678956123');
INSERT INTO CUSTOMERS VALUES (6, 'ATB', '0984758888');
INSERT INTO CUSTOMERS VALUES (7, 'Adidas', '0505050147');

INSERT INTO PROJECTS VALUES (1, 'Support OTP Bank', 'Ukraine', 1, 1);
INSERT INTO PROJECTS VALUES (2, 'Support PrivatBank', 'Ukraine', 2, 2);
INSERT INTO PROJECTS VALUES (3, 'Support Monobank', 'Ukraine', 3, 3);
INSERT INTO PROJECTS VALUES (4, 'Support Metro', 'Poland', 4, 4);
INSERT INTO PROJECTS VALUES (5, 'Support Ashan', 'Poland',5, 5);
INSERT INTO PROJECTS VALUES (6, 'Support ATB', 'Ukraine', 6, 6);
INSERT INTO PROJECTS VALUES (7, 'Support Adidas', 'Germany',7, 7);

INSERT INTO DEVELOPERS_PROJECTS VALUES (1, 1);
INSERT INTO DEVELOPERS_PROJECTS VALUES (1, 2);
INSERT INTO DEVELOPERS_PROJECTS VALUES (2, 3);
INSERT INTO DEVELOPERS_PROJECTS VALUES (2, 4);
INSERT INTO DEVELOPERS_PROJECTS VALUES (3, 5);
INSERT INTO DEVELOPERS_PROJECTS VALUES (3, 4);
INSERT INTO DEVELOPERS_PROJECTS VALUES (4, 6);
INSERT INTO DEVELOPERS_PROJECTS VALUES (4, 1);
INSERT INTO DEVELOPERS_PROJECTS VALUES (5, 7);
INSERT INTO DEVELOPERS_PROJECTS VALUES (6, 3);
INSERT INTO DEVELOPERS_PROJECTS VALUES (6, 6);

UPDATE projects
SET date_of_creation='2017-01-01'
WHERE projects.id=1;
UPDATE projects
SET date_of_creation='2018-04-05'
WHERE projects.id=2;
UPDATE projects
SET date_of_creation='2013-08-25'
WHERE projects.id=3;
UPDATE projects
SET date_of_creation='2021-02-01'
WHERE projects.id=4;
UPDATE projects
SET date_of_creation='2020-10-18'
WHERE projects.id=5;
UPDATE projects
SET date_of_creation='2019-01-27'
WHERE projects.id=6;
UPDATE projects
SET date_of_creation='2018-11-09'
WHERE projects.id=7;